#!/usr/bin/env python3
"""
kwork_check_auth.py — проверка и выполнение входа на kwork.ru.

Открывает Chrome на странице проектов kwork.ru.
Если пользователь не авторизован — ждёт ручного входа.
После входа сохраняет cookies в cookies.txt.

Exit codes:
    0 — авторизация выполнена, cookies сохранены
    1 — пользователь закрыл окно, авторизация не выполнена
"""
import sys
from pathlib import Path

from playwright.sync_api import sync_playwright

SCRIPT_DIR = Path(__file__).parent.resolve()
ROOT = SCRIPT_DIR.parent.resolve()
COOKIES_FILE = ROOT / "cookies.txt"

USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

LOGIN_SELECTOR = "a[href*='login'], a[href*='registration'], :text('Войти'), :text('Вход')"


def load_cookies(context, cookies_path: Path) -> int:
    """Загружает cookies из Netscape-файла в Playwright-контекст. Возвращает кол-во."""
    if not cookies_path.exists():
        return -1
    pairs = []
    with open(cookies_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 7:
                continue
            domain, _, path, secure, expires, name, value = parts[:7]
            cookie = {
                "name": name,
                "value": value,
                "domain": domain,
                "path": path or "/",
            }
            if secure == "TRUE":
                cookie["secure"] = True
            try:
                exp_int = int(expires) if expires and expires != "0" else -1
            except ValueError:
                exp_int = -1
            if exp_int > 0:
                cookie["expires"] = exp_int
            pairs.append(cookie)
    if pairs:
        context.add_cookies(pairs)
    return len(pairs)


def save_cookies(context) -> bool:
    """Сохраняет cookies из контекста в cookies.txt"""
    cookies = context.cookies()
    if not cookies:
        print("[ERROR] Cookies пусты", file=sys.stderr)
        return False
    with open(COOKIES_FILE, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by kwork_check_auth.py\n")
        for c in cookies:
            domain = c.get("domain", "")
            if domain.startswith("."):
                domain = domain[1:]
            secure = "TRUE" if c.get("secure") else "FALSE"
            expires = str(int(c.get("expires", 0))) if c.get("expires") else "0"
            f.write(f"{domain}\tTRUE\t/\tFALSE\t{expires}\t{c['name']}\t{c['value']}\n")
    print(f"[OK] Cookies сохранены в {COOKIES_FILE.name} ({len(cookies)} шт.)")
    return True


def main() -> int:
    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=False,
            slow_mo=50,
            args=["--disable-blink-features=AutomationControlled"],
        )
        try:
            context = browser.new_context(
                viewport={"width": 1280, "height": 800},
                locale="ru-RU",
                user_agent=USER_AGENT,
            )
            load_cookies(context, COOKIES_FILE)
            page = context.new_page()
            print("[INFO] Открываю kwork.ru...")
            page.goto("https://kwork.ru/projects?fc=46", wait_until="domcontentloaded", timeout=30000)

            # Проверка авторизации: ищем кнопку входа
            if page.locator(LOGIN_SELECTOR).count() == 0:
                print("[OK] Вы уже авторизованы на kwork.ru.")
                save_cookies(context)
                return 0

            # Кнопка входа есть — не авторизован, ждём логина
            print(f"\n{'='*60}", flush=True)
            print(f"[LOGIN] ⚠️  Требуется вход на kwork.ru", flush=True)
            print(f"[LOGIN] Введите логин/пароль в открывшемся окне Chrome.", flush=True)
            print(f"[LOGIN] Закройте окно, чтобы отменить.", flush=True)
            print(f"{'='*60}\n", flush=True)

            try:
                # Ждём, пока кнопка входа исчезнет (пользователь вошёл)
                page.locator(LOGIN_SELECTOR).first.wait_for(state="hidden", timeout=0)
                print("[OK] Вход выполнен!")
                save_cookies(context)
                return 0
            except Exception:
                print("[LOGIN] Окно браузера закрыто. Авторизация не выполнена.", file=sys.stderr)
                return 1
        finally:
            try:
                browser.close()
            except Exception:
                pass


if __name__ == "__main__":
    sys.exit(main())